
== ??

Estilo: Ligero
[source]
----
  6   6   5       56
6.  5   5   44434.   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
3   4  334  32   334    556
  3  4.   4.   2     44     6
~~~~~~~~~~~~~~~~~~~~~~~~~~
334  322   334    556
    4.   2     44     6
----




== Abandonada

Andres Miraval | Estilo: Ligero
[source]
----
  6   5      5        5.  5.   6
6   5   4444   4.4344   5.  55   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
3.   3.  32   3.       5.  5.   6
  33   4.   33  4.4344   5.  55   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
  6   5        5.  5.   6
6   5   4.4344   5.  55   6
----

audio::audio/abandonada.m4a[]
Como la canción te vas quedando, sola y esperando, mal abandonada. (BIS)

Mañana quedaran, tus ojos más tristes, tu alma ausente, hemos de olvidarte. (BIS)

Hay mi palomita, sola y esperando, mal abandonada. (BIS)

== Abelito

Estilo: Ligero
[source]
----
  2   333   33-322   233
4   2     3        1     33-3
>>>
3     5      5      56
 3444   55-5   4334    6
~~~~~~~~~~~~~~~~~~~~~~~~~~
  5      5     3333223
5   4433   55-5       33-3
>>>
3     5      5      56
 3444   55-5   4334    6
~~~~~~~~~~~~~~~~~~~~~~~~~~
332      5      56
    33-5   4334    6
----


Parte I::
Hoy cuanto vale un veintisiete, es como el sol en su lago, lucero inmenso del mañana, es lo que vale un veintisiete.
+
Cuando pregunten a los Apus, el Cancharani respondera, el Azoguine, Huajsapata, cuanto vale un veintisiete.
+
Con sicuris, nunca olvides Abelito.

Parte II::
Si quieren callar a tu pueblo, defenderás buen guerrero, Sicuri apu sartañiri, toma el valor veintisiete.
+
Por eso cuando te reclamen, levantarás el Jake Aru, el gran vocero de tu pueblo, toma el valor veintisiete.
+
Con sicuris, nunca olvides Abelito.

== Agua Milagro

Filiberto Calderon | Estilo: Huayno calmado
[source]
----
322   33   33   5556  6
   22   44   44     6   56
~~~~~~~~~~~~~~~~~~~~~~~~~~
   5556  6   5   33  5556  6
544    6   5   44  44    6   56
~~~~~~~~~~~~~~~~~~~~~~~~~~
322    33    33    5556   6
    22    44    44      6   56
----

audio::audio/agua-milagro.m4a[]
Parte I::
Cariño sobre cariño, yo te conocí conimeñita linda de mis amores.
+
Agua milagro brindaste, como una prueba de amor, pero tu me traicionaste sin compasión.
+
Ay Conimeñita linda de mi corazón, pero tú me traicionaste sin compasión.

Parte II::
Entre los cactus de flores blancas, negrita llorabas amargamente, tu decepción.
+
Agua milagro brindaste, como una prueba de amor, pero tú me traicionaste sin compasión.
+
Ay Conimeñita linda de mi corazón, pero tú me traicionaste sin compasión.

Parte III::
La soledad y la muerte son para mi, lamentos del alma en vida que he de llevar.
+
Porque si pasión existe se puede amar con frenesí, pero a lo lejos tu olvido persiste igual.
+
Por eso te ruego que no vuelvas más a mí, porque a lo lejos tu olvido persiste igual.

== Alturas de Huallpacayu

? | Estilo: ?
[source]
----
   2222   3   334
444     2   2     4
~~~~~~~~~~~~~~~~~~~~~~~~~~
    3333   4   556
4444     3   44   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
  6   5   5   556
6   5   4   54   6
----

audio::audio/[]
Allá en lo alto, de un cerro lejano (BIS) +
Dejé mi nombre como un recuerdo (BIS) +
Y si no regreso, ni tú ya te acuerdes (BIS)

Suri manachu, sonk'o suwaychu (BIS) +
Sinchi llakiquni ripukuy munaypi (BIS) +
Y si no regreso, ni tú ya te acuerdes (BIS)

== Ayma Italaque

? | Estilo: Italaque
[source]
----
3     4   5
  444   4   44
~~~~~~~~~~~~~~~~~~~~~~~~~~
    545
434     5
~~~~~~~~~~~~~~~~~~~~~~~~~~
222...222
666...666
~~~~~~~~~~~~~~~~~~~~~~~~~~
  5   56...6   6   5   5   4
4   5        5   5   4   4   4
>>>
5       4   565   5   6   5
 4...43   4     4   5   5   5
----

audio::audio/[]


== Chuyma Marka

Liber Cahui Bustincio | Estilo: Ligero
[source]
----
211-11  2-33      233
      11    2-11-1   34
~~~~~~~~~~~~~~~~~~~~~~~~~~
  33   33-2     5    55-5     7
4   34     3-44   55     5-66   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
   5   55-5     7
55   44    5-66   6
----




== Cuando me vaya (kencha moza)

Liber Cahui Bustincio | Estilo: Ligero
[source]
----
  3  3333  2..  2   3    3
4   3    2    1   2   32   4
~~~~~~~~~~~~~~~~~~~~~~~~~~
3   4   4   34    3   4   556
  3   4   3    4..  3   44   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
   7   6    5    3   4   556
66   6   55   4..  3   44    6
----

audio::audio/cuando-me-vaya.mp4[]


== Cunataquiraqui

Markasata | Estilo: ?
[source]
----
    5  3334-32  32       556
5-44  4       2   4443-44   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
4-43       556
    4-43-44   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
  6   5     556
6   5   4344   6
----

audio::audio/[]
Parte I::
Cunataquiraqui negra, chuymama churista, negra chuymama churista (BIS)
+
Mayuru, payuru, munasiñataqui (BIS)
+
Ahora si no quieres, ándate con otro. Y si no me quieres, ándate con otro.

Parte II::
Eso de quererte, negra, tiene una cosita, negra, tiene una cosita (BIS)
+
Entra por los ojos, negra y en el alma queda (BIS)
+
Ahora si no quieres, ándate con otro. Y si no me quieres, ándate con otro.

== Gabrielita

Estilo: Ligero
[source]
----
  5   6   6    5
4   5   5   55
>>>
  3-22     3   34
44    22-2   3    4
~~~~~~~~~~~~~~~~~~~~~~~~~~
3-22    3   34
    222   3    44
>>>
543   3     56
   44   3443   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
  6   5   543   3     56
6   5   44   44   3443   66
----


Parte I::
Linda Gabriela de mi vida, tus ojos, tus labios son mi debilidad.
+
Besarte, abrazarte son sueños para mi, que si te vas tu ausencia de dolor me matará.
+
No puedo olvidarte flor 27 en mis recuerdos te llevaré.

Parte II::
Me hiere el frío de tu mirada, tan cerca ufana, ciegas mi corazón.
+
No muestras cariño, pero tu aroma aquí, en mi corazón, haces que en mis noches llore por ti.
+
Linda gabrielita, tu amor espero, como angel que cure mi soledad.
+
No puedo olvidarte flor 27 en mis recuerdos te llevaré.

== Hermosa Italaqueña

Taypi Agia | Estilo: Italaque
[source]
----
  6   5   54   554   5
6   5   4    4    44   4-6
>>>
6   5   54      5    56
  5   4    4444   54    6
~~~~~~~~~~~~~~~~~~~~~~~~~~
33    554   33   554
  4444   44   444   44-6
>>>
6   5   5-4    5   56
  5   4    444   54   6
----

audio::audio/[]
Parte I::
Hermosa italaqueña de trenzas largas, pollera azul +
Llegas con el sol de la mañana a las fiestas de San Roque.
+
Dime morena de labios dulces, si tu cariño ya tiene dueño +
En tus brazos quiero sentir el susurro de las kantutas.

Parte II::
Hacia el lago se pierde el sol, llevando penas sin desatar +
A Italaque yo volveré una mañana del mes de agosto.
+
Miro al cielo, veo tu rostro y no es el viento quien te despeina +
Son las caricias de un sicuri, que no dejará de amarte.

== Huata Imilla (tengo mi perrito) Qheny

? | Estilo: ?
[source]
----
  5   23333-23     3
5   44        3433   4
~~~~~~~~~~~~~~~~~~~~~~~~~~
  5    3    3    5    77
5   44   33   44   56    56
~~~~~~~~~~~~~~~~~~~~~~~~~~
  5     3    5    77
5   433   44   56    56
----

audio::audio/kheni.m4a[]


== Inca Caja

Qheny Sankayo | Estilo: ?
[source]
----
2-111   2   2   1  2332   5
      1   2   1   1    ~4   4
~~~~~~~~~~~~~~~~~~~~~~~~~~
 3332   5  ~5665   6
4     4  ~44     5   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
   ~5665   6
5-44     5   6
----

audio::audio/[]


== JJ

Estilo: Ligero
[source]
----
3   2   3   2     32    56
  2   2   2   122    44    6
~~~~~~~~~~~~~~~~~~~~~~~~~~
 333   55    333
4   34   5556   34
>>>
55      5    56
  55565   443   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
2   3    56
  2   43    6
----

audio::audio/jj.mpeg[]


== Los Chitos

Qheny Sankayo | Estilo: ?
[source]
----
222  3   3     55   6
   2   3   3-44   5   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
  5      5    3    55   6
5   44-55  44   344   5   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
322  3   4     55    6
   2   3   4443   55   6
----

audio::audio/[]


== Mañanas del 14 de julio

Moco Moco | Estilo: ?
[source]
----
  7   6   5   55     333  4
66  6   5   4   444-4   3   4
~~~~~~~~~~~~~~~~~~~~~~~~~~
 333   4      5-444
4    3   4-434      4
>>>
5    6555   6
 5434     5   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
   6555   6
765     5   6
----

audio::audio/[]
Parte I::
En las mañanas del 14 de julio, mi corazón se rompió
+
Al ver como tú le sonreías, como le entregabas, tu cariño, mi corazón se quebró
+
Ingrata, mi corazón se quebró.

Parte II::
Iluso yo por entregarle mi alma, a quien no lo mereció
+
Solo para cosechar tristezas, para pasar al olvido eterno, de quien no lo mereció
+
Mi alma, que ella no mereció.

== Marcha Italaque

? | Estilo: Italaque
[source]
----
     3   44-55   4
3-44   3       3   43
~~~~~~~~~~~~~~~~~~~~~~~~~~
4-33  4     4   544   5
    3   433   4     4   555
~~~~~~~~~~~~~~~~~~~~~~~~~~
777   6     5   444   4   3
    6   555   4     4   3   33
>>>
433   4     4   544  5
    3   433   4    4   555
----

audio::audio/[]


== Mi regreso

Wara | Estilo: ?
[source]
----
   7   6   5     44   443   2222
66   6   5   4444   4     2
>>>
   23332    5    56
211     444   54    6
~~~~~~~~~~~~~~~~~~~~~~~~~~
44  55-5  44444-3332    5    56
  4     4           4444  5-4   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
7   7   5      5   56
  6   5   4444   54   6
----

audio::audio/[]
De muy lejos he venido, para cumplir la promesa +
Porque te quiero con el alma mi bella Kantutita

Muchos lugares visité, y otra gente conocí +
Y he regresado nuevamente, por que yo te quiero a ti

Quiero vivirme contigo, toda la vida, en los andes, mi tierra +
Siempre yo te voy a querer, mi bella kantutita.

== Nostalgia

Andres Miraval Centón | Estilo: Ligero
[source]
----
33   32    5   6    7
   3   444   5   66   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
  565     5     7
54   5554   566   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
  5     5   6    7
55  444   5   66   6
----

audio::audio/nostalgia.mpeg[]
Parte I::
Quien tiene tu ensueño, paloma que el viento susurra.
+
Tenía una amante ilusión, crecida en el tiempo. +
+
Y si no estaba, gris era la vida.

Parte II::
Quiso el destino, un día robarme su amor.
+
La pena es más pena y su amor lejano y ausente.
+
Sin su cariño, tristes son los días.

== Palla Palla 27

Andres Miraval | Estilo: Marcha?
[source]
----
2   1   1   232  23   3
  1   1   1    1    3   4
~~~~~~~~~~~~~~~~~~~~~~~~~~
  5  5   3   32   5   665  6
5  4   4   34  34  455   5   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
77    55    665   6
   55    44     5   6
----

audio::audio/[]
 

== Patat Jalari

Estilo: Ligero
[source]
----
 3333   5556     3
4    34     4333   4
>>>
5    77765   6
 5556      5   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
   5        5         3
34   4...34   4...4333
>>>
  5     77765   6
4   5556      5   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
  5     77765   6
54  5556      5   6
----




== Qhepama Sarta (voy tras tuyo)

? | Estilo: ?
[source]
----
  5   3    5    555-6   56
5  444  34  45-4     55    6
~~~~~~~~~~~~~~~~~~~~~~~~~~
   5      5     555-6   56
54   45-4   45-4     55    6
~~~~~~~~~~~~~~~~~~~~~~~~~~
   5     555-6    56
44   45-4     5-5    6
----

audio::audio/[]
Parte I::
Llaqui queptatakiwa, qhepama sarta, inaj munitaspa asina, imillita.
+
Qhepama sarta, jaypu chiw'jama, inaj munitaspa sasina, pankarita.
+
Jani ukhamamti, jinay jinay sarjañani, imillita.

Parte II::
Llevando penas y olvidos, voy tras tuyo, pensando que tu me querras, palomita.
+
Corazón roto, hecho una sombra, pensando que tu me querras, voy tras tuyo.
+
Dulce paloma, vamos, vamonos conmigo, no seas asi.

== Suspiros

Estilo: Ligero
[source]
----
  6   5       5.  5   4  33.33  3..322   334
6   5   44.44   4.  4   3     3.      22    4.
>>>
      55  6.666   5    6.
54443   5.      4   55   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
322  334  3 23       55  6..666 5   6.
   22   4. 2  4.54443  5.      4 55   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
  6   5   33   4        55   6.666   5   6.
6   5  44    3   4.54443   5.      4  55   6
----


Parte I::
Esta melodía yo quiero cantar, cual un pentagrama del corazón, notas que expresan mi ansiedad, mi sentimiento y mi verdad, cariño mío eres mi bien. (BIS)
+
A cada instante en mi soledad, suspiro por ti, mi vida entera yo te la di, porque te quise con el alma. (BIS)
+
Mi vida entera yo te la di, porque te quise con el alma.(BIS)

Parte II::
Yo no sé si acaso tú piensas en mi, o esta melodía te hará suspirar, tan solo vida quiero pensar, que la distancia jamás será, el mal que arrastre nuestro querer. (BIS)
+
Sin tu cariño no he de vivir, total para que, si eres aymara de corazón, hasta en el tiempo te esperaré. (BIS)
+
Si eres aymara de corazón, hasta en el tiempo te esperaré. (BIS)

== Torero

Anónimo | Estilo: Ligero
[source]
----
  4    33   2    33
4   33   33   22    33
~~~~~~~~~~~~~~~~~~~~~~~~~~
3    44    4    55
  33    44   44    55
~~~~~~~~~~~~~~~~~~~~~~~~~~
7    55    4    55
  55    44   44    55
----

audio::audio/[]


== Tres (3) de Mayo

Cojata | Estilo: Ligero
[source]
----
2111  23   21   23   33  45
    1   33    1   33   3   55
~~~~~~~~~~~~~~~~~~~~~~~~~~
  5   4   3    33   45
5   4   3   33    3    55
~~~~~~~~~~~~~~~~~~~~~~~~~~
21   23    33   45
   1    33    3    55
----

audio::audio/[]


== Tres de mayo

Estilo: Ligero
[source]
----
 33332   323      3   434      5   656
4      2    43333   3    54444   5    6
~~~~~~~~~~~~~~~~~~~~~~~~~~
  44443   434       5   656
4       3     54444   5     6
~~~~~~~~~~~~~~~~~~~~~~~~~~
         3   434       5   656
4333...3   3     54444   5     6
~~~~~~~~~~~~~~~~~~~~~~~~~~
   5   656
544  5     6
----


Parte I::
En una noche de tres de mayo, tuve la suerte de conocerte, tuve la suerte de haberte querido. (BIS)
+
Tú me decías olvidar todo, olvidaremos todo lo pasado. (BIS)
+
Negrita, todo lo pasado.(BIS)

Parte II::
Y yo seguro en tus palabras y esperanzado en tus promesas, viví un tiempo lleno de ilusiones. (BIS)
+
Ilusiones que vas borrando, con tus hechos que son falsedades. (BIS)
+
Negrita, que son falsedades. (BIS)

Parte III::
Que se acabe, que se termine, la triste historia de este cariño, la triste historia de nuestro romance. (BIS)
+
Que no me miren esos tus ojos, que no me besen ya tus labios rojos. (BIS)
+
Negrita, ya tus labios rojos. (BIS)

== Virginia

Gustavo Alatrista | Estilo: Ligero
[source]
----
  3   3   23-22      34
4   3   2       1-22    4
~~~~~~~~~~~~~~~~~~~~~~~~~~
33     5    33     5
  3444   56    344   56-4
>>>
4   4   3     56
  4   3   4443   6
~~~~~~~~~~~~~~~~~~~~~~~~~~
2   3   3      56
  2   3   4443    6
----

audio::audio/virginia.mpeg[]
Parte I::
Voy a pedir hoy, que doblen las campanas de mi corazón, porque mañana me muero y tú me has dejado sin tu amor.
+
Virginia tú eres la causa, de este cariño que mata con tus crueles desatinos, yo ya estoy muriendo por tu amor.
+
Eres tu virginia, la causa de este amor.

Parte II::
Del cielo voy a enviarte mis caricias y mi devoción, para que te vengas pronto a quererme más y más que ayer.
+
Virginia tú eres la causa, de este cariño que mata, con tus crueles desatinos yo ya estoy muriendo por tu amor
