# [[source]]
# name = ""
# author = ""
# type = "Calmado" | "Ligero" | "Diana" | "Marcha"
# numerofonia = """ """
# img = ".png"
# audio = ""
# lyrics = """ """

## fecha de composición = 1992, Enero 12

[[source]]
name = "JJ"
type = "Ligero"
numerofonia = """
3   2   3   2     32    56
  2   2   2   122    44    6
~~~~~~~~~~
 333   55    333   55      5    56
4   34   5556   34   55565   443   6
~~~~~~~~~~
2   3    56
  2   43    6"""
audio = "jj.mpeg"


[[source]]
name = "Abandonada"
author = "Andres Miraval"
type = "Ligero"
numerofonia = """
  6   5      5        5.  5.   6
6   5   4444   4.4344   5.  55   6
~~~~~~~~~~
3.   3.  32   3.       5.  5.   6
  33   4.   33  4.4344   5.  55   6
~~~~~~~~~~
  6   5        5.  5.   6
6   5   4.4344   5.  55   6"""
lyrics = """Como la canción te vas quedando, +
sola y esperando, mal abandonada. (BIS)

Mañana quedaran, tus ojos más tristes, +
tu alma ausente, hemos de olvidarte. (BIS)

Hay mi palomita, sola y +
esperando, mal abandonada. (BIS)"""

[[source]]
name = "??"
type = "Ligero"
numerofonia = """
  6   6   5       56
6.  5   5   44434.   6
~~~~~~~~~~
3   4  334  32   334    556
  3  4.   4.   2     44     6
~~~~~~~~~~
334  322   334    556
    4.   2     44     6"""

[[source]]
name = "Chuyma Marka"
author = "Liber Cahui Bustincio"
type = "Ligero"
numerofonia = """
211-11  2-33      233
      11    2-11-1   34
~~~~~~~~~~
  33   33-2     5    55-5     7
4   34     3-44   55     5-66   6
~~~~~~~~~~
   5   55-5     7
55   44    5-66   6"""

[[source]]
name = "Cuando me vaya (kencha moza)"
author = "Liber Cahui Bustincio"
type = "Ligero"
numerofonia = """
  3  3333  2..  2   3    3
4   3    2    1   2   32   4
~~~~~~~~~~
3   4   4   34    3   4   556
  3   4   3    4..  3   44   6
~~~~~~~~~~
   7   6    5    3   4   556
66   6   55   4..  3   44    6"""
audio = "cuando-me-vaya.mp4"

[[source]]
name = "Agua Milagro"
author = "Filiberto Calderon"
type = "Calmado"
numerofonia = """
322   33   33   5556  6
   22   44   44     6   56
~~~~~~~~~~
   5556  6   5   33  5556  6
544    6   5   44  44    6   56
~~~~~~~~~~
322    33    33    5556   6
    22    44    44      6   56"""
lyrics = """Parte I::
Cariño sobre cariño, yo te conocí +
conimeñita linda de mis amores.
+
Agua milagro brindaste +
como una prueba de amor, +
pero tu me traicionaste +
sin compasión.
+
Ay Conimeñita linda de mi corazón, +
pero tú me traicionaste sin compasión.

Parte II::
Entre los cactus de flores blancas, negrita +
llorabas amargamente, tu decepción.
+
Agua milagro brindaste +
como una prueba de amor, +
pero tu me traicionaste +
sin compasión.
+
Ay Conimeñita linda de mi corazón, +
pero tú me traicionaste sin compasión.

Parte III::
La soledad y la muerte son para mi, +
lamentos del alma en vida que he de llevar.
+
Porque si pasión existe se puede amar con frenesí, +
pero a lo lejos tu olvido persiste igual.
+
Por eso te ruego que no vuelvas más a mí +
porque a lo lejos tu olvido persiste igual."""

[[source]]
name = "Patat Jalari"
type = "Ligero"
numerofonia = """
 3333   5556     3
4    34     4333   4
>>>
5    77765   6
 5556      5   6
~~~~~~~~~~
   5        5         3
34   4...34   4...4333
>>>
  5     77765   6
4   5556      5   6
~~~~~~~~~~
  5     77765   6
54  5556      5   6"""

[[source]]
name = "Tres de mayo"
type = "Ligero"
numerofonia = """
 33332   323      3   434      5   656
4      2    43333   3    54444   5    6
~~~~~~~~~~
  44443   434       5   656
4       3     54444   5     6
~~~~~~~~~~
         3   434       5   656
4333...3   3     54444   5     6
~~~~~~~~~~
   5   656
544  5     6"""
lyrics = """Parte I::
En una noche de tres de mayo, +
tuve la suerte de conocerte, tuve +
la suerte de haberte querido. (BIS)
+
Tú me decías olvidar todo, +
olvidaremos todo lo pasado. (BIS)
+
Negrita, todo lo pasado.(BIS)

Parte II::
Y yo seguro en tus palabras y +
esperanzado en tus promesas, viví +
un tiempo lleno de ilusiones. (BIS)
+
Ilusiones que vas borrando, con +
tus hechos que son falsedades. (BIS)
+
Negrita, que son falsedades. (BIS)

Parte III::
Que se acabe, que se termine, la +
triste historia de este cariño, la +
triste historia de nuestro romance. (BIS)
+
Que no me miren esos tus ojos, +
que no me besen ya tus labios rojos. (BIS)
+
Negrita, ya tus labios rojos. (BIS)"""

[[source]]
name = "Abelito"
type = "Ligero"
numerofonia = """
  2   333   33-322   233
4   2     3        1     33-3
>>>
3     5      5      56
 3444   55-5   4334    6
~~~~~~~~~~
  5      5     3333223
5   4433   55-5       33-3
>>>
3     5      5      56
 3444   55-5   4334    6
~~~~~~~~~~
332      5      56
    33-5   4334    6"""
lyrics = """Parte I::
Hoy cuanto vale un veintisiete, +
es como el sol en su lago +
lucero inmenso del mañana, +
es lo que vale un veintisiete. +
+
Cuando pregunten a los Apus, +
el Cancharani respondera, +
el Azoguine, Huajsapata, +
cuanto vale un veintisiete. +
+
Con sicuris, nunca olvides Abelito. +

Parte II::
Si quieren callar a tu pueblo, +
defenderás buen guerrero, +
Sicuri apu sartañiri +
toma el valor veintisiete. +
+
Por eso cuando te reclamen, +
levantarás el Jake Aru, +
el gran vocero de tu pueblo, +
toma el valor veintisiete. +
+
Con sicuris, nunca olvides Abelito."""

[[source]]
name = "Virginia"
author = "Gustavo Alatrista"
type = "Ligero"
numerofonia = """
  3   3   23-22      34
4   3   2       1-22    4
~~~~~~~~~~
33     5    33     5
  3444   56    344   56-4
>>>
4   4   3     56
  4   3   4443   6
~~~~~~~~~~
2   3   3      56
  2   3   4443    6"""
audio = "virginia.mpeg"
lyrics = """Parte I::
Voy a pedir hoy, que doblen las +
campanas de mi corazón, +
porque mañana me muero +
y tú me has dejado sin tu amor
+
Virginia tú eres la causa, +
de este cariño que mata con tus +
crueles desatinos, yo ya estoy +
muriendo por tu amor
+
Eres tu virginia +
la causa de este amor

Parte II::
Del cielo voy a enviarte +
mis caricias y mi devoción +
para que te vengas pronto +
a quererme más y más que ayer
+
Virginia tú eres la causa, +
de este cariño que mata +
con tus crueles desatinos +
yo ya estoy muriendo +
por tu amor"""

[[source]]
name = "Suspiros"
type = "Ligero"
numerofonia = """
  6   5       5.  5   4  33.33  3..322   334
6   5   44.44   4.  4   3     3.      22    4.
>>>
      55  6.666   5    6.
54443   5.      4   55   6
~~~~~~~~~~
322  334  3 23       55  6..666 5   6.
   22   4. 2  4.54443  5.      4 55   6
~~~~~~~~~~
  6   5   33   4        55   6.666   5   6.
6   5  44    3   4.54443   5.      4  55   6"""
lyrics = """
Parte I::
Esta melodía yo quiero cantar, +
cual un pentagrama del corazón +
notas que expresan mi ansiedad, +
mi sentimiento y mi verdad, +
cariño mío eres mi bien. (BIS)
+
A cada instante en mi soledad, +
suspiro por ti, mi vida entera yo +
te la di, porque te quise con el +
alma. (BIS)
+
Mi vida entera yo te la di, porque +
te quise con el alma.(BIS)

Parte II::
Yo no sé si acaso tú piensas en +
mi, o esta melodía te hará +
suspirar, tan solo vida quiero +
pensar, que la distancia jamás +
será, el mal que arrastre nuestro +
querer. (BIS)
+
Sin tu cariño no he de vivir, total +
para que, si eres aymara de +
corazón, hasta en el tiempo te +
esperaré. (BIS)
+
Si eres aymara de corazón, hasta +
en el tiempo te esperaré. (BIS)"""

[[source]]
name = "Torero"
author = "Anónimo"
type = "Ligero"
numerofonia = """
  4    33   2    33
4   33   33   22    33
~~~~~~~~~~
3    44    4    55
  33    44   44    55
~~~~~~~~~~
7    55    4    55
  55    44   44    55"""
audio = ""

[[source]]
name = "Tres (3) de Mayo"
author = "Cojata"
type = "Ligero"
numerofonia = """
2111  23   21   23   33  45
    1   33    1   33   3   55
~~~~~~~~~~
  5   4   3    33   45
5   4   3   33    3    55
~~~~~~~~~~
21   23    33   45
   1    33    3    55"""
audio = ""

[[source]]
name = "Hermosa Italaqueña"
author = "Taypi Agia"
type = "Italaque"
numerofonia = """
  6   5   54   554   5
6   5   4    4    44   4-6
>>>
6   5   54      5    56
  5   4    4444   54    6
~~~~~~~~~~
33    554   33   554
  4444   44   444   44-6
>>>
6   5   5-4    5   56
  5   4    444   54   6"""
audio = ""
lyrics = """
Hermosa italaqueña +
De trenzas largas, pollera azul +
Llegas con el sol de la mañana +
A las fiestas de San Roque.

Dime morena de labios dulces +
Si tu cariño ya tiene dueño +
En tus brazos quiero sentir +
El susurro de las kantutas.

Hacia el lago se pierde el sol +
Llevando penas sin desatar +
A Italaque yo volveré +
Una mañana del mes de agosto.

Miro al cielo, veo tu rostro +
Y no es el viento quien te despeina +
Son las caricias de un sicuri +
Que no dejará de amarte."""

[[source]]
name = "Mañanas del 14 de julio"
author = "Moco Moco"
type = "?"
numerofonia = """
  7   6   5   55     333  4
66  6   5   4   444-4   3   4
~~~~~~~~~~
 333   4      5-444
4    3   4-434      4
>>>
5    6555   6
 5434     5   6
~~~~~~~~~~
   6555   6
765     5   6
"""
audio = ""
lyrics = """
Parte I::
En las mañanas del 14 de julio, mi corazón se rompió +
Al ver como tú le sonreías, como le entregabas, tu cariño, mi corazón se quebró +
Ingrata, mi corazón se quebró.

Parte II::
Iluso yo por entregarle mi alma, a quien no lo mereció +
Solo para cosechar tristezas, para pasar al olvido eterno, de quien no lo mereció +
Mi alma, que ella no mereció."""

[[source]]
name = "Alturas de Huallpacayu"
author = "?"
type = "?"
numerofonia = """
   2222   3   334
444     2   2     4
~~~~~~~~~~
    3333   4   556
4444     3   44   6
~~~~~~~~~~
  6   5   5   556
6   5   4   54   6"""
audio = ""
lyrics = """
Allá en lo alto, de un cerro lejano (BIS) +
Dejé mi nombre como un recuerdo (BIS) +
Y si no regreso, ni tú ya te acuerdes (BIS)

Suri manachu, sonk'o suwaychu (BIS) +
Sinchi llakiquni ripukuy munaypi (BIS) +
Y si no regreso, ni tú ya te acuerdes (BIS)"""

[[source]]
name = "Cunataquiraqui"
author = "Markasata"
type = "?"
numerofonia = """
    5  3334-32  32       556
5-44  4       2   4443-44   6
~~~~~~~~~~
4-43       556
    4-43-44   6
~~~~~~~~~~
  6   5     556
6   5   4344   6"""
audio = ""
lyrics = """
Parte I::
Cunataquiraqui negra, chuymama churista, negra chuymama churista (BIS) +
Mayuru, payuru, munasiñataqui (BIS) +
Ahora si no quieres, ándate con otro. Y si no me quieres, ándate con otro.

Parte II::
Eso de quererte, negra, tiene una cosita, negra, tiene una cosita (BIS) +
Entra por los ojos, negra y en el alma queda (BIS) +
Ahora si no quieres, ándate con otro. Y si no me quieres, ándate con otro."""

[[source]]
name = "Mi regreso"
author = "Wara"
type = "?"
numerofonia = """
   7   6   5     44   443   2222
66   6   5   4444   4     2
>>>
   23332    5    56
211     444   54    6
~~~~~~~~~~
44  55-5  44444-3332    5    56
  4     4           4444  5-4   6
~~~~~~~~~~
7   7   5      5   56
  6   5   4444   54   6"""
audio = ""
lyrics = """
De muy lejos he venido, para cumplir la promesa +
Porque te quiero con el alma mi bella Kantutita

Muchos lugares visité, y otra gente conocí +
Y he regresado nuevamente, por que yo te quiero a ti

Quiero vivirme contigo, toda la vida +
En los andes, mi tierra

Siempre yo te voy a querer +
Mi bella kantutita."""

[[source]]
name = "Marcha Italaque"
author = "?"
type = "Italaque"
numerofonia = """
     3   44-55   4
3-44   3       3   43
~~~~~~~~~~
4-33  4     4   544   5
    3   433   4     4   555
~~~~~~~~~~
777   6     5   444   4   3
    6   555   4     4   3   33
>>>
433   4     4   544  5
    3   433   4    4   555"""
audio = ""

[[source]]
name = "Ayma Italaque"
author = "?"
type = "Italaque"
numerofonia = """
3     4   5
  444   4   44
~~~~~~~~~~
    545
434     5
~~~~~~~~~~
222...222
666...666
~~~~~~~~~~
  5   56...6   6   5   5   4
4   5        5   5   4   4   4
>>>
5       4   565   5   6   5
 4...43   4     4   5   5   5"""
audio = ""

[[source]]
name = "Nostalgia"
author = "Andres Miraval Centón"
type = "Ligero"
numerofonia = """
33   32    5   6    7
   3   444   5   66   6
~~~~~~~~~~
  565     5     7
54   5554   566   6
~~~~~~~~~~
  5     5   6    7
55  444   5   66   6"""
audio = "nostalgia.mpeg"
lyrics = """
Parte I::
Quien tiene tu ensueño, paloma +
que el viento susurra.
+
Tenía una amante ilusión +
crecida en el tiempo. +
+
Y si no estaba +
gris era la vida.

Parte II::
Quiso el destino, un día +
robarme su amor.
+
La pena es más pena y su amor +
lejano y ausente.
+
Sin su cariño +
tristes son los días."""