# [[source]]
# name = " "
# author = "?"
# type = "Calmado" | "Ligero" | "Diana" | "Marcha"
# numerofonia = """ """
# img = ".png"
# audio = ""
# lyrics = """ """

[[source]]
name = "JJ"
type = "Ligero"
numerofonia = """
3   2   3   2     32    56
  2   2   2   122    44    6
---
 333   55    333   55      5    56
4   34   5556   34   55565   443   6
---
2   3    56 
  2   43    6"""
audio = "jj.mpeg"


[[source]]
name = "Abandonada"
author = "Andres Miraval"
type = "Ligero"
numerofonia = """
  6   5      5        5.  5.   6
6   5   4444   4.4344   5.  55   6
---
3.   3.  32   3.       5.  5.   6
  33   4.   33  4.4344   5.  55   6
---
  6   5        5.  5.   6
6   5   4.4344   5.  55   6"""
lyrics = """Como la canción te vas quedando, +
sola y esperando, mal abandonada. (BIS)

Mañana quedaran, tus ojos más tristes, +
tu alma ausente, hemos de olvidarte. (BIS)

Hay mi palomita, sola y +
esperando, mal abandonada. (BIS)"""


[[source]]
name = "Huayno?"
type = "Ligero"
numerofonia = """
  6   6   5       56
6.  5   5   44434.   6
---
3   4  334  32   334    556
  3  4.   4.   2     44     6
---
334  322   334    556
    4.   2     44     6"""


[[source]]
name = "Chuyma Marka"
author = "Liber Cahui Bustincio"
type = "Ligero"
numerofonia = """ """
img = "chuyma-marka.png"


[[source]]
name = "Cuando me vaya (kencha moza)"
author = "Liber Cahui Bustincio"
type = "Ligero"
numerofonia = """ """
img = "cuando-me-vaya.jpeg"
audio = "cuando-me-vaya.mp4"


[[source]]
name = "Agua Milagro"
author = "Filiberto Calderon"
type = "Calmado"
numerofonia = """ """
img = "agua-milagro.png"
lyrics = """Parte I::
Cariño sobre cariño, yo te conocí +
conimeñita linda de mis amores.
+
Agua milagro brindaste +
como una prueba de amor, +
pero tu me traicionaste +
sin compasión.
+
Ay Conimeñita linda de mi corazón, +
pero tú me traicionaste sin compasión.

Parte II::

Entre los cactus de flores blancas, negrita +
llorabas amargamente, tu decepción.
+
Agua milagro brindaste +
como una prueba de amor, +
pero tu me traicionaste +
sin compasión.
+
Ay Conimeñita linda de mi corazón, +
pero tú me traicionaste sin compasión.

Parte III::
La soledad y la muerte son para mi, +
lamentos del alma en vida que he de llevar.
+
Porque si pasión existe se puede amar con frenesí, +
pero a lo lejos tu olvido persiste igual.
+
Por eso te ruego que no vuelvas más a mí +
porque a lo lejos tu olvido persiste igual."""


[[source]]
name = "Patat Jalari"
author = "?"
type = "Ligero"
numerofonia = """
 3333  5556    3   5    77765  6
4    34    4333  4  5556     5   6
---
  5     5       3   5    77765  6
34  4.34  4.4333  4  5556     5   6
---
  5     77765   6
54  5556      5   6"""
audio = ".mp3"
lyrics = """ """


[[source]]
name = "Cruz de mayo?"
author = "?"
type = "Ligero"
numerofonia = """
 33332 323     3   434     5  656
4     2   43333  3    54444  5   6
---
 44443  434      5  656
4      3    54444  5   6
---
   5   656
544  5     6"""
audio = ".mp3"
lyrics = """ """